
import BlogPost from "../../BlogPost"

export default function () {
    return (
        <BlogPost title="Rewriting I Can Has Web with Wintersmith">
            <p>I recently rewrote this website using <a href="http://wintersmith.io/">Wintersmith</a>, and in this post I'll detail the process; the ideas I had initially, the choices I faced, the decisions I took, and how the final result turned out to be. (The latest code can be seen at <a href="https://github.com/megoth/icanhasweb">megoth/icanhasweb</a>.)</p>
<p>The post will not be going through how to set up a new wintersmith blog, there are other good resources on that (like <a href="https://github.com/jnordberg/wintersmith#quick-start">here</a>, <a href="http://davidtucker.net/articles/introduction-to-wintersmith/">here</a>, and <a href="http://www.sitepoint.com/getting-started-wintersmith-nodejs-static-site-generator/">here</a>).</p>
<p><strong>TL;DR: I've rewritten this website using Wintersmith. The content types are blog posts, projects, talks, and my cv. The three former supports tagging, which is made possible with a monkey patched version of wintersmith-tag. I also wrote a bit of scripts, using webpack to organize and bundle it, and included a couple of services (Disqus and Google Analytics).</strong></p>
<p>The website was powered by two wordpress installations. Just to be clear, I wasn't dissapointed with Wordpress per se, but I disliked the fact that it is written in PHP (which is not my language of choice), and I wasn't going to invest time in utilizing its powers and flexibility (for example, I know of its <a href="https://wordpress.org/about/features/">Custom Content Types</a>, which probably would have been sufficient for a lot of my needs).</p>
<p>On the other hand, I have been exploring Wintersmith a lot in a couple of other projects, and although the documentation leaves much to be wanted, I'm very satisfied with the experience. It's easy to set up, easy to change, and has some community that is building some nifty tools. Not so much going for it that I would choose it in a more serious endeavor (read: making something where a lot of money is involved), but for my personal use it's good enough.</p>
<h2>Initial setup</h2>
<p>My outset was to move all of my blog posts to a unified blog and reuse my minimalist theme (with some changes, to explore some CSS features). As the blog functionality was the biggest unknown for me, I decided to start with that by using the default blog template (which is the default template, so if you want to try it out, just check out <a href="https://github.com/jnordberg/wintersmith#quick-start">Wintersmiths quick-start</a>). That gave me a simple frontpage with pagination of posts, a RSS feed, and articles, which is an overview of all posts by year and month.</p>
<p>Next I cloned the <a href="https://github.com/megoth/minimalist">minimalist repo</a> into the project, and created a simple grunt setup using <a href="https://github.com/firstandthird/load-grunt-config">load-grunt-config</a> and <a href="https://github.com/sindresorhus/load-grunt-tasks">load-grunt-tasks</a>. With that in place, I created the following tasks:</p>
<ul>
<li><a href="https://github.com/gruntjs/grunt-contrib-clean">clean</a>: to delete files between builds</li>
<li>&lt;strike&gt;<a href="https://github.com/gruntjs/grunt-contrib-copy">copy</a>: to copy resources that aren't moved with Wintersmith&lt;/strike&gt; (I later realized Wintersmith handles all copying I need ^_^)</li>
<li><a href="https://github.com/gruntjs/grunt-contrib-sass">sass</a>: to handle sass-to-css from the minimalist project</li>
<li><a href="https://github.com/gruntjs/grunt-contrib-watch">watch</a>: because developing without it is pain</li>
<li><a href="https://github.com/davidtucker/grunt-wintersmith">wintersmith</a>: to trigger wintersmith builds</li>
</ul>
<h2>Design</h2>
<p>Paired with <a href="https://www.npmjs.com/package/live-server">live-server</a> which I run in the build-folder (which refreshes the website after each build), I had my development-setup in place. It made the refitting of minimalist a pleasure to do, and in the process I learned a little about <a href="http://www.w3.org/TR/css-grid-1/">CSS grid</a> and <a href="http://www.w3.org/TR/css-flexbox-1/">CSS flex</a> (I learned a lot from <a href="https://24ways.org/2015/grid-flexbox-box-alignment-our-new-system-for-layout/">a post by Rachel Andreas on 24 ways</a> and <a href="https://css-tricks.com/snippets/css/a-guide-to-flexbox/">this guide by Chris Coyier on CSS-Tricks</a>).</p>
<p>As part of the refitting I also fixed the aside-parts on the frontpage; a small about-section, a photo of myself, a list of public profiles, a list of selected projects, and a list content on this site. That was done by simply copying the content from the old site, modifying it to the jade syntax in index.pug.</p>
<h2>Importing old posts and tags</h2>
<p>While working I realized I wanted to append tags to articles, as I had done that for most of previous blog posts. <a href="https://www.npmjs.com/package/wintersmith-tag">wintersmith-tag</a> was suitable for this, and it proved to be a simple plug-n-play. It was really fun to see everything click into place.</p>
<p>It was not so fun moving all the old blog posts. I figured I could move one post every two minutes, and didn't think I had that many. It turned out to be 115 posts. Some time into it I was kind of pissed that I didn't just write a program to do it. And I got even more pissed at myself afterwards when I realized there is actually written <a href="https://github.com/davidbanham/wp-to-wintersmith">a tool for it</a>... Well, no point in crying over spilt milk.</p>
<h2>Comments and projects</h2>
<p>Moving the posts, tedious as it was, other ideas formed in my head; To enable comments for the new blog posts, and to showcase my projects.</p>
<p>For the former I started looking at <a href="https://disqus.com/">Disqus</a>, and while searching for them, was deviously lured by <a href="https://www.spot.im/">Spot.IM</a> who had bought an ad-spot when searching for disqus. Although I'm not fan of such devious tactics, I am a fan of trying new things, so I gave them a shot. Realizing they was way to invasive for my taste, I went back to Disqus.</p>
<p>Disqus is simple to set up, simply insert a script, and make sure that you generate some proper strings for it to use, and your set. I didn't want to enable commenting on all of my old posts, so I made a rule to only enable Disqus on articles that didn't link to an original URL. That worked out well.</p>
<p>To showcase my projects I was thinking I could just put some pages into another folder (blog posts are located in articles by default) and started wondering if I could plug tags into those pages as well. wintersmith-tag doesn't support that out of the box, but I figured I could simply <a href="https://en.wikipedia.org/wiki/Monkey_patch">monkey patch</a> it.</p>
<h2>Monkey patching wintersmith-tag</h2>
<p>It turned out that copying src/index.coffee from wintersmith-tag to plugins/tags.coffee and modifying the necessary bits was really easy. The original author took care in reusing functionality, so I simply had to extend the code one place, namely the getArticles-function; I extended it so that it could take an array of strings, instead of just a simple string, and run a map-function over the array that returned a list of directories (which was what it was suppose to return, albeit only sub-directories from one given directory).</p>
<p>I realized the monkey patch fucked up the pagination in the tag-template, as it was difficult to mix two types of contents. So I turned off pagination altogether by increasing the number of posts per page to 100. I also split the listing of pages into projects and blog posts explicitly, so that projects are listed at the top and blog posts below (I'm more keen to show off my code than my blog posts).</p>
<p>Having support for tags from multiple directories, I wrote a page for each of the public repositories that I thought interesting to share. I added a status to each, setting them to either active (still being maintained at various pace), inactive (uncomplete, not being maintained for various reasons), and complete.</p>
<h2>Setting up my CV</h2>
<p>When nearing the end of the projects, I also realized I wanted to rewrite my CV-page, so that it was somewhat updated (still not done with that though) and reflected the new design. That meant introducing a bit of JavaScript, including the use of 3rd party services (namely <a href="http://zeptojs.com/">Zepto</a>). I've fallen a bit in love with <a href="https://webpack.github.io/">webpack</a> lately, so I plugged that into the system, introducing <a href="https://github.com/webpack/grunt-webpack">a new task as well</a>. A bit overkill perhaps, but I was figuring that if I wanted to expand JavaScript later on, it would be much easier to do it &quot;properly&quot; at once. It didn't hurt that I then also had bundling and optimization in place.</p>
<p>I tried to take care in making the functionality accesible (although I probably need to add some more ARIA roles). I'm thinking of revisiting the script later, after researching a bit more on accessibility.</p>
<h2>Setting up analytics and introducing a cookie-warning</h2>
<p>Next I wanted to introduce Google Analytics to the page. That was also very easy to set up (simply following the steps set out by Google), but I realized that Analytics, as well as Disqus, probably uses cookies, and that I should probably adhere the <a href="https://www.cookielaw.org/the-cookie-law/">cookie law</a> (and respect that some people really don't like having unauthorized cookies on their computer without notification). So I added a bit of text in the footer, and created a small script that handled the &quot;Click this button to never again show this boring warning about cookies&quot;-functionality.</p>
<p>Lo and behold - the decision to use webpack paid off. I created a new entry for the global script, and set up webpack to create a common file for common scripts - namely Zepto. I also made use of <a href="https://github.com/js-cookie/js-cookie">js-cookie</a> to get simple cookie-handling.</p>
<h2>Talks</h2>
<p>Having the project-texts in mind, I realized that some of them would be better presented as simply talks. They shared a lot of the same data (a repository and optionally a URL), but could also have a date attached to it. So I created a new folder named talks, moved the content that beloged there, and set up some new templates and linked to the new section from the main navigation.</p>
<p>As I had already monkey patched the tags functionality, it was a small step to include the new folder into the array of content to list tags from.</p>
<h2>Conclusion</h2>
<p>I'm quite satisfied with the new website, and hope to be able to add more content to it in the time to come. I'm very happy with how easy it is to modify, but will try to <a href="http://www.w3.org/Provider/Style/URI.html">keep my URIs cool</a>.</p>
<p>For now there are a severe lack of images, which has a very good reason - I'm trying to keep my webpages small. But I'll probably experiment with some <a href="https://responsiveimages.org/">responsive images</a> in the near future.</p>
<p>I want to focus on writing more, and have a couple of projects in mind. Some of it will probably show up here, at least I'll write about it here at some point.</p>
<p>The only negative with the new setup is the fact that every time I want to update the site I have to upload a bunch of files. But as I don't update my site that often anyway, it's a small price to pay.</p>

        </BlogPost>
    )
}