
import BlogPost from "../../BlogPost"

export default function () {
    return (
        <BlogPost title="Projects 2013">
            <p>I like to keep myself occupied, previously exemplified by my involvement in several student organizations while I studied (one in which I still partake with my time and effort, albeit in diminishing manner). Since I completed my master thesis this fall, I've tried to limit my involvement, and concentrate on work and getting on route with my life as a professional. I believe myself to be on the right path now, and hope to increase my involvement once again, as this post will describe.</p>
<p>So what do I hope to involve myself in? Well, there are several projects out there, several events I want to attend, and several talks I want to hold. So lets just get on with it.</p>
<h2>Projects</h2>
<p>&lt;strong&gt;&lt;a href=&quot;https://github.com/holderdeord/&quot;&gt;Holder de ord&lt;/a&gt; (HDO):&lt;/strong&gt; During the last months of my study, I kept an eye out for HDO. This not-for-profit, politically independent entrepreneurship aims to be a watchdog on Norwegian politics, specifically by analyzing the data shared by the Storting, the Norwegian Parliament, and share it in a discoverable and easily consumable manner.</p>
<p>I quickly joined HDO when the thesis was completed, but I quickly realized I couldn’t spare the time necessary. For the spring of 2013 I’ll make a better effort to change this, and I’ve already signed me up for their monthly hackatons (you can too; &lt;a href=&quot;http://www.facebook.com/events/141520302664699/&quot;&gt;January&lt;/a&gt;, &lt;a href=&quot;http://www.facebook.com/events/476487999069718/&quot;&gt;February&lt;/a&gt;, &lt;a href=&quot;http://www.facebook.com/events/111087629060034/&quot;&gt;March&lt;/a&gt;, and &lt;a href=&quot;http://www.facebook.com/events/392300807514529/&quot;&gt;April&lt;/a&gt; is out!).</p>
<p>&lt;strong&gt;&lt;a href=&quot;https://github.com/megoth/graphitejs&quot;&gt;graphite.js&lt;/a&gt;:&lt;/strong&gt; I really want to keep up the development of the project that came out of my thesis. I’ve also been approached by one of the author of JSON-LD, &lt;a href=&quot;https://twitter.com/markuslanthaler&quot;&gt;Markus Lanthaler&lt;/a&gt;, asking me to update &lt;a href=&quot;https://github.com/megoth/graphitejs/blob/master/src/graphite/rdfparser/jsonld.js&quot;&gt;my JSON-LD processor&lt;/a&gt;, so first and foremost I’ll try to do that.</p>
<p>&lt;strong&gt;&lt;a href=&quot;http://tg.ifi.uio.no/&quot;&gt;UiO: Campus TG&lt;/a&gt;:&lt;/strong&gt; &lt;a href=&quot;http://www.gathering.org/&quot;&gt;The Gathering&lt;/a&gt; (TG) is an annual event at Vikingskipet, Hamar (Norway). Basicly it’s a huge computer party, with five thousand participants, mostly teenage boys. I’ll be joining the efforts of UiO to convince these young, bright minds to study at UiO. As part of this effort, my plan is to give three lectures; one that aims to teach basic JavaScript for beginners, and two that will involve a tutorial. As part of this, there are three minor (<em>cough</em> famous last words <em>cough</em>) projects:</p>
<ul>
<li>A to-do list (yeah, I know, original) made with basic JavaScript, for which the purpose is to be used as a teaching tool; The data types involved, the setup, the decisions, etc, will be part of a tutorial I hope to go through. The first lecture will go through a non-persistent to-do list (perhaps only “saving” to cookies); the second part will be a collaboration with one of the other lecturers, who will create a server application with another programming language that will talk with the to-do app.</li>
<li>Tetris! Yeah, I know, another original idea; But the goal is to use it to gain knowledge on &lt;a href=&quot;http://www.w3.org/TR/gamepad/&quot;&gt;W3′s gamepad specs&lt;/a&gt;, and probably work with &lt;a href=&quot;http://www.gamepadjs.com/&quot;&gt;gamepad.js&lt;/a&gt;. I think that can be a cool demo to show at TG.</li>
<li>Rubik’s Cube: Based on my learning on the gamepad &lt;abbr title=&quot;Application Programming Interface&quot;&gt;API&lt;/abbr&gt;, I want to embellish the concept by combining it with &lt;a href=&quot;https://github.com/mrdoob/three.js/&quot;&gt;three.js&lt;/a&gt;, and create a Rubik’s Cube in 3D, and enabling controls with a gamepad (and keyboard of course).</li>
</ul>
<p>The two latter projects require me to buy a gamepad. &lt;a href=&quot;#disqus_thread&quot;&gt;Any advice are appreciated&lt;/a&gt;. Also, to start my work with Tetris, I’ll look into the &lt;a href=&quot;git://git.neuf.no/tetris.git&quot;&gt;Tetris project hosted at git.neuf.no&lt;/a&gt;. Any hints at other projects are also appreciated.</p>
<h3>Edit</h3>
<p>I also hope to contribute to &lt;a href=&quot;https://github.com/steinjak/LessDocs&quot;&gt;LessDocs&lt;/a&gt;, a project I’ve neglected for to long already. It’s initiated by my colleague Stein Jakob Nordbø, and we hope to make use of it at the center.</p>
<h2>Events</h2>
<p>This will depend more on what my workplace can afford, but hopefully I can be on all of the following:</p>
<p>&lt;strong&gt;&lt;a href=&quot;http://qconlondon.com/&quot;&gt;QCon London&lt;/a&gt;:&lt;/strong&gt; This is already decided, and the whole development team at the center will participate. Really looking forward to this, as it will probably be the first I participate as a non-student.</p>
<p>&lt;strong&gt;&lt;a href=&quot;http://www.ndcoslo.com/&quot;&gt;Norwegian Developer Conference&lt;/a&gt;:&lt;/strong&gt; Considering the expensive trip to London, this is more uncertain, but I’ll keep my fingers crossed.</p>
<p>&lt;strong&gt;&lt;a href=&quot;http://webrebels.org/&quot;&gt;Web Rebels&lt;/a&gt;:&lt;/strong&gt; A conference focusing on web development in Oslo? I got to be a part of it!</p>
<h2>Talks</h2>
<p>This might be too ambitious, but I hope that my lectures on TG are positive, and that it may improve my presentation skills. Apart from these lectures, I have no concrete goals, but the workplace is always interested in being taught about the developments within web technologies, so I’ll probably give some talks there.</p>
<h3>Edit</h3>
<p>Apart from the talks I would like to do, there are a bunch of arenas I’m going to follow in hope to find interesting talks. I’m a fan of &lt;a href=&quot;http://www.meetup.com/&quot;&gt;Meetup&lt;/a&gt;, and can recommend several groups, such as &lt;a href=&quot;http://www.meetup.com/framsia/&quot;&gt;framsia&lt;/a&gt;, &lt;a href=&quot;http://www.baksia.org/&quot;&gt;baksia&lt;/a&gt;, and &lt;a href=&quot;http://www.meetup.com/osloopendata/&quot;&gt;Oslo Open Data Forum&lt;/a&gt;. I also hope to go to more talks by &lt;a href=&quot;http://www.meetup.com/Oslo-Socially-Functional/&quot;&gt;Oslo “Socially Functional Programmers” #OsloSFP&lt;/a&gt; and &lt;a href=&quot;http://www.meetup.com/GDGOslo/&quot;&gt;GDG Oslo&lt;/a&gt;.</p>

        </BlogPost>
    )
}