
import BlogPost from "../../BlogPost"

export default function () {
    return (
        <BlogPost title="Tur til Irland">
            

<table style="float:right;width:194px;">
<tbody><tr>
<td style="background:transparent url('http://picasaweb.google.com/f/img/transparent_album_background.gif') no-repeat scroll left center;height:194px;" align="center"><a href="http://picasaweb.google.com/arne.hassel/Irland2007"><img src="http://lh5.google.com/arne.hassel/Rqp3SkphVdE/AAAAAAAABCA/zBNHR7cW7gU/s160-c/Irland2007.jpg" style="margin:1px 0 0 4px;" alt="Ved å trykke på bildet kommer du til galleriet jeg har satt opp for bilder fra turen" height="160" width="160" /></a></td>
</tr>
<tr>
<td style="text-align:center;font-family:arial,sans-serif;font-size:11px;"><a href="http://picasaweb.google.com/arne.hassel/Irland2007">Irland 2007</a></td>
</tr>
</tbody></table>
<p>Dette er en beretning om min reise til <a href="http://en.wikipedia.org/wiki/Ireland">Irland</a>, som jeg tilbringte sammen med 6 venner. Utenlandsturer er et tiltak som har gitt blod på tann blant den nære vennekrets, og 2-3 av dem har tatt det på seg å ta initiativet som trengs, og lokker oss andre med på ulike destinasjoner. For min egen del er turen gjennom Riga, Estland og Sverige et resultat av dette, mens turene til London og Edinburgh var to jeg dessverre ikke fikk tid til. Og flere blir det forhåpentligvis. Men denne teksten skal altså ta for seg den til Irland.</p>

<p>I tillegg til bildene som ligger på <a href="http://picasaweb.google.com/arne.hassel/Irland2007">min picasaweb-konto</a>, så har også en av mine venner lagt opp bilder fra turen på <a href="http://picasaweb.google.com/andersdale/Irland">sin konto</a>.</p>
<p>Det var en kort og god reise, fem dager i alt, hvor vi boltret oss i kultur av alskens slag i <a href="http://no.wikipedia.org/wiki/Dublin">Dublin</a> (drikkekulturen sådann), men som også ga oss muligheten til å oppleve <a href="http://en.wikipedia.org/wiki/Inishmore">Inishmore</a>, en av øyene i <a href="http://en.wikipedia.org/wiki/Aran_Islands">Isle of Aran</a>, som er på vestkysten. Dette bringte oss i tog på tvers av landet, slik at vi også fikk sett noe av naturen.</p>
<p>Irland er kjent for sin natur, så dette var noe vi ønsket å få med oss. På det punktet ga ikke togturen oss noe mersmak. Men om togturen hadde skuffet oss, så gjorde Inishmore opp for dette, og vel så det. Vi var så heldige å få sol denne dagen, og vi bestemte oss da for å leie sykkler. En av de beste avgjørelsene vi tok i løpet av turen, for friheten som dette resulterte i var simpelthen herligheten selv. Inishmore er en langdratt øy fra nordvest mot sørøst, med hovedsaklig tre topper, som ligger nesten på linje gjennom øya. De to største ligger mot vest, mens Killronan, havnen og den største/eneste byen på øya, ligger mellom den midterste og den toppen mot øst. Hit kom vi med ferja, og her startet vår tur med innleide sykkler (koster 10 euro). Etter å ha surret oss frem til <a href="http://www.hostelworld.com/hosteldetails.php/TheArtistsHostel-AranIslands-16892">Artist Hostel</a> (jeg og en kamerat surra ekstra lenge, da vi klarte å sykle forbi Hostelet i vel 10 min), startet vi vår tur over øya.</p>
<p>Først på besøkslista vår var et fort som på den midterste høyden. Etter en oppoverbakke med en helling jeg aldri har opplevd maken til, var vi fremme ved byggningen (som jeg dessverre ikke husker navnet på nå). Utsikten som bredte seg utover herfra var herlig, og ganske klassisk for øyas landskaper generelt, konkluderte vi med senere. Et innfløkt mønster av steingjerder snodde seg her og der, avskjærte noen lapper med gress her og noen lapper der. Alt i alt skapte dette et intrikat detaljert bilde av grønt og grått, med en skjønnhet bare Irland kan skape.</p>
<p>Utover skjønnheten skapte steingjerdene enda en mulighet – det gikk nemlig veier gjennom landskapet. Ikke vanlige veier, men gamle, umerka steinveier som skjærte gjennom øya. Personlig er jeg ikke himmelfallen for sykkling, men “utforskingen” av denne løypa var virkelig en høydare. Men det anbefales at man bruker en sykkel med gode støtdempere. To i gruppen var ikke så heldig, og måtte belage seg på en ekstra kronglete og humpete løype.</p>
<p>Etter å ha hoppet og snike seg gjennom steinveiene, kom vi til en av de vanlige veiene gjennom øya, og bega oss videre ut mot <a href="http://en.wikipedia.org/wiki/Dun_Aengus">Dun Aengus</a>, som var hovedmålet vårt for dagen. Før vi var fremme utforsket vi en del av øyas kyststripe, som i størsteparten består av, iallefall vestdelen av øya, lave steinpartier og klipper. Ulikt de norske svaberg var denne kysten rå, oppkuttet, og med dype furer som vitnet om naturkrefter i arbeid. Enda et skue vi alle var glade å ha fått med oss. Turen gikk videre gjennom av øyas små landsbyer, forbi en av de få sandstrendene og videre opp øyas turistsenter, hvor vi måtte betale for å komme til fortet (1.20 euro for studenter og barn, 2.20 for alle andre). Den siste biten gikk til fots, opp en lang, trappelignende høyde.</p>
<p>Dun Aengus er et av Europas eldste steinfort, og består av tre høye steingjerder i en halvsirkel. Grunnen til at sirkelen ikke er hel er enkel: Fortet ligger halvveis over en klippehøyde. 87 meter rett ned! For dem som har vært på prekestolen kan det å sitte på kanten med beina hengende utenfor forløpe seg en kjent følelse. For de fleste av oss var turen mot kanten sen og kalkulert, og sittinga meget møysommelig. For under oss slo det veldig atlanterhavet inn, og krefter vi ikke kunne forstå var kontinuerlig i arbeid i denne veldige klippen. For dem som ønsker et lite innblikk i hvordan dette forløper seg, besøk <a href="http://www.lookaroundireland.com/araninteractive/dunaengus.htm">denne siden</a> til Look Around Ireland.</p>
<p>Etter besøket på fortet gikk turen fort tilbake til Hostelet. Her møtte vi en jente fra Frankrike, som vi innviterte med på middag. For sent fant vi ut at all matservering på øya ble stengt halv 10. Sultne og maktesløse overfor denne åpenbaring fant vi ut at det bare var en ting å gjøre, nemlig å drikke seg mette på Irlands mest berømte øl; <a href="http://en.wikipedia.org/wiki/Guinness">Guinness</a>. For dem som ikke vet har Guinness en fylde og volum som enkelt utgjør et måltid i seg selv, noe som var en lykke for sultne, øltørste ungdommer fra Norge. Unødvendig å si, var kvelden en meget fornøyelig en, godt innbundet i historier, spørsmål om Frankrike og generelt pisspreik, gjerne alle i samme åndedrett. Når jeg i tillegg avslører at gruppen vår besto utelukkende av gutter, så sier det kanskje noe om dimensjonen av dialogen som gikk for seg denne kvelden.</p>
<p>Dagen etter gikk vår tur tilbake til Irland. Først var vi innom <a href="http://en.wikipedia.org/wiki/Galway">Galway</a>, som er byen vi dro gjennom for å komme til Inishmore. Selv om byen i seg selv er veldig fin og sikkert verdt en dag eller to, føler jeg ikke at vi tilbragte nok tid i den til å si noe bemerkelsesverdig om den. Heller skjedde det ikke noe bemerkelsesverdig, med kanskje unntak i den lille turen vi hadde rundt havnen, hvor vi så i underkant av 100 svaner (vi prøvde å telle) langs moloen. Det merkeligste var dog en pelikan vi så, som sto stand utenfor et hus og, virka det som, ventet på at noen skulle komme ut med en godbit eller to. Den var lite sjenert, og hadde ikke noe imot at vi nærmet oss. Vi ville dog ikke  utfordre skjebnen, og trakk oss tilbake da det var en eller to meter mellom oss.</p>
<p>Til nå har jeg viet mesteparten av teksten til Inishmore, som i mine øyne var turens absolutte høydepunkt. Dublin, hvor vi tilbrakte mesteparten av vår tid (underkant av 4 dager), har kanskje ikke fått den plass den fortjener. Da vi ankom Dublin flyplass tok det liten tid for oss å finne maxitaxi inn til byen, da vi var 7 stykker. Bilen vi satt i hadde bare plass til 6, så sistemann ble plassert mellom setene. Høyst ureglementert, men hvis det var noe vi fikk inntrykk av i løpet av turen, var at regler er så som så å følge når man er Irland. Ikke sjeldent så vi biler gjennom byens brogater, i en fart som må ha oversteget hva som var lovlig.</p>
<p>Ellers gikk mesteparten av turen vår til fots gjennom Dublins mange gater og broer. Blant annet krysset vi Ha’Penny, en bro som har fått navnet sitt fra den gamle broavgiften, half penny. Vi besøkte også Guinness Store House, et veldig bygg formet som en gigantisk <a href="http://en.wikipedia.org/wiki/Pint">Pint</a>, som er engelskmennenes ølglass. Den selvguida turen gjennom dette bygget var imponerende, og tok for seg alt som kunne sies om Guinness’ produksjon, historie og kultur. De to sistnevnte er viktige punkt å få med seg, da Irlands befolkning har en imponerende/omfattende kultur med konsum av det sorte brygg.</p>
<p>Det faste holdepunktet vårt for alle dagene i Dublin var <a href="http://www.isaacs.ie/isaacs_hostel/">Isaac Hostel</a>. Dette var alt vi kunne forvente av et Hostel, og kanskje litt til. Vi benyttet oss ikke så mye av det, da vi de fleste dagene var ute på byen, men hostellet hadde en kjeller som var til tider veldig sosial og hadde en hyggelig atmosfære over seg. Generelt virket hostellet sosialt og hyggelig, med unntak i toalettene, som til tider hadde stoppet, og som ofte var nedpissa. Vi fikk heller ikke særlig kontakt med hostellets klientell, da vi for det meste gikk for oss selv. Vi hadde en som vi fikk snakka med litt, som tilbringte rom med oss en natt. Han var fra Israel, og var akkurat ferdig med sin tre år lange tjeneste i hæren. Nå hadde han en måned fri, og hadde brukt den til å gå rundt i Irland. Han ville bli medisinstudent, og høstet noen tips fra kameraten vår som lå i sengen under ham, som går på medisinstudier.</p>
<p>Hostellet var ellers, som sagt, det vi kunne forventet av et hostel. Vårt rom lå 10 meter fra toglinja, noe som ikke førte til nevneverdig bråk, da det sjeldent gikk tog i løpet av natta. Det som derimot voldet bråk, var ungdommene som flyttet ut av hostellets inngangsparti da det stengte ti, for å fortsette sin sosialisering i form av drikke og snakking; veldig høylydt snakking! Det var kanskje bare meg som ble plaget nevneverdig av dette, da jeg sov rett ved vinduet, men jeg tror jeg er berettiget når jeg sier at amerikanere generelt snakker jævlig høyt! (jeg kan summere opp mesteparten av samtalen de hadde, da de hadde et desibelnivå langt høyere enn resten). Men men, sove fikk man nå gjort til slutt, og når det kommer til det så er det jo ikke soving som er det viktigste på en utenlandstur.</p>
<p>Et høydepunkt som jeg vil trekke frem er en middag vi hadde på en av Dublins mange kinarestauranter. Vi hadde delt oss i to grupper, en i tre og en i fire. Jeg var med i den som besto av fire, og sammen følte vi for litt kinamat (det skal sies at Irland ikke har noe nevneverdig kjøkken, ikke som jeg opplevde iallefall). Vi bestilte en samlemeny som rett og slett gikk ut på “Dinner for 4″. For 11 euro hver fikk vi et majestetisk måltid bestående av kylling, and, gris, okse og kongereker, alle med hver sin spesielle saus. Min favoritt var anden samt grisen, med kylling og kongereker på en god annenplass. Dessverre var de andre rettene så sterke (jeg svettet som en gal til tider) at okseretten forsvant i smakspekteret. I tillegg til dette hadde vi imponerende forretter i form av kyllingsuppe og vårruller. Alt dette akkompagnert av tv-skjermer langs veggen som viste koreanske tv-show med kinesisk undertekst. Etter middagen formelig rullet vi oss ut av restauranten, bare misfornøyd med at vi ikke fikk spist opp alt av maten, for det lå igjen i underkant av en tallerken.</p>
<p>Vi tok oss ellers turen til <a href="http://en.wikipedia.org/wiki/Trinity_College%2C_Dublin">Trinity College</a>, som er Irlands eldste universitet. Vi også innom <a href="http://no.wikipedia.org/wiki/Dublin_Castle">Dublin Castle</a>, som blant annet står oppe gamle deler av et fort fra da vikingene var i Dublin. Ellers fikk vi med oss statuen av <a href="http://en.wikipedia.org/wiki/Molly_Malone">Molly Malone</a>, en kjent, barmfager figur fra irske sanger. Vi var også innom <a href="http://en.wikipedia.org/wiki/Temple_Bar,_Dublin">Temple Bar</a> ved flere anledninger, og konsumerte Guinness så vel som Irish Coffee, samt mangt, mangt annet.</p>
<p>Alt i alt vil jeg anbefale Dublin og, ikke minst, Inishmore som gode reisemål. Prisnivået er litt under det som er i Norge, men i utgangspunktet bør man beregne det samme (ølet er selvsagt noe billigere, men på turiststedene er det ofte 2-3 euro dyrere, noe som gjør at ølprisen faller inn like under det norske). Det bør dog bemerkes at begge stedene bør nytes i godt solskinn, noe som sjeldent er regelen i Irland (dette er iallefall inntrykket jeg har). Har man solen i ryggen er det det eneste utgangspunktet man trenger for å nyte stedene, for begge tilbyr kultur, historie og imponerende syn. Og, om man skulle føle for det, så er det rikelig med brygg å konsumere.</p>

        </BlogPost>
    )
}