
import BlogPost from "../../BlogPost"

export default function () {
    return (
        <BlogPost title="Medier og informasjon, kvalitet og kvantitet">
            

<p>Tankerekken jeg vil ta for meg i denne teksten kommer etter å ha lest kronikken “<a href="http://www.aftenposten.no/meninger/kronikker/article1668636.ece">Sakene mediene glemmer</a>” til Trygve Aas Olsen som var i Aftenposten lørdag 2. mars. Etter å ha lest den navnebroren “<a href="http://www.vg.no/pub/vgart.hbs?artid=168806">Saker mediene glemmer</a>“, skrevet av Guri Hjeltnes og trykket i VG 5. mars, spinte tankene bare videre.</p>
<span class="more"></span>
<p>For dem som ikke gidder å ta for seg artiklene, som jeg mener er meget godt skrevne og tar for seg en mediekritikk jeg syns er meget sunn, lager jeg en meget kort oppsummering her. Fagbladet Journalisten satte i fjor i gang et prosjekt som tar for seg saker som media ikke gir nok oppmerksomhet. Dette prosjektet er inspirert av etablerte organisasjoner som <a href="http://www.projectcensored.org/">Project Censored</a> og <a href="http://www.kl-medien.de/ina/">Initiative Nachrichtenaufklärung</a>. Dette er altså saker som burde fortjent mer oppmerksomhet på grunnlag av deres betydning for folket. Men tankerekken min tar mer feste i et av Guris avsnitt.</p>
<blockquote><p>Juryen mottok 92 forslag, fra lokale temaer til internasjonale forhold. En erfaring juryen gjorde, var at mange saker som ble meldt på, ikke var underrapport eller «glemt». Faktisk var ingen av sakene helt «glemt», det fantes omtale i en eller form av mediene. Men dimensjoneringen av stoffet kan diskuteres.</p></blockquote>
<p><strong>Informasjonskaoset</strong></p>
<p>Min tanke slår seg ikke til ro. Jeg begynner å stille meg selv spørsmål og mange problemstillinger dukker opp. La meg prøve å male et så beskrivende bilde som mulig. Jeg innser at dette kan virke som usammenhengende babbel, men aksepter det for nå og prøv å følg med i tankerekkene mine.</p>
<p>Nyheter. Tekster med informasjon om nye begivenheter. Jeg prøver meg med den definisjonen. En definisjon med vidt innhold, som lett kan <a href="http://stavelin.com/blog/2006/12/12/er-nettaviser-fullverdige-aviser/">diskuteres</a>. Men like fullt en definisjon som kan brukes som et utgangspunkt.</p>
<p>Medier. Informasjonskanaler. Grensesnitt til informasjon, være dette ny eller gammel. Som mennesker er det våre sanser teknologien må rette sitt grensesnitt imot. Altså er vi begrenset til media som appelerer til vår hørsel, syn, smaksorganer og følelseorganer ellers. Videre er informasjonen avhengig i at vi kan tolke signalene som blir sendt, forstå dem og behandle dem slik at de skaper en mening i vårt hode (hele denne veien gjør at man nesten skulle ønske seg en Matrix-maskin hvor man bare kunne putte inn informasjonen rett til hodet).</p>
<p>For å komme ut av det forrige avsnittet: Det er lang vei for massemediene å gå før de får sin informasjon fram til oss. Og da har jeg ikke engang begynt å snakke om produksjonsleddet som er før alt kommer klart, ryddig og pakket klar for oss. Men slik er det nå blitt, og i den moderne verden er det big business å drive med media. Og som i all annen business <a href="http://www.globaljournalist.org/magazine/2005-1/outsourcing.html">kutter man der man kan</a>, gjennom f.eks. <a href="http://en.wikipedia.org/wiki/Outsourcing">outsourcing</a>.</p>
<p>En av de store revolusjonene som har kommet gjennom internett er at det ikke er lenger behov for et massivt apparat bak informasjonsformidlingen. Hvermansen kan lage sin egen weblogg nå, faktisk øker antallet raskere og raskere – i et nærmest sinnsvakt tempo. Og med dette ser vi også at mengden informasjon eskalerer. Hendelser skjer, blir skrevet om og blir nærmest sendt i et masseproduksjonsbånd mellom forskjellige aktører som prosesserer informasjonen og spytter ut enda mer “ny” informasjon. Alt for å få flest lesere, tjene mest penger eller bare være “den første” med <a href="http://en.wikipedia.org/wiki/Scoop_%28term%29">scoopet</a>.</p>
<p>Dette er ikke noe som helst nytt. Konseptet bak dette er heller ikke nytt. Det nye i miksen er hvor raskt denne prosessen skjer. Ved å revolusjonere internett som publiseringsplattform gjennom forenkling har man skapt like mange nye speil som det finnes personer der ute som behersker de nye publiseringsplattformene. Og det er et tall som bare øker og øker, virker det som.</p>
<p>Jeg sier ikke at speileffekten nødvendigvis er noe dumt. En artikkel som tar grunnlag i en eller flere tekster kan videreforedle nyhetens innhold gjennom forfatterens innsikt og kunnskap. Men på lik linje kan en nyhet bli fordervet og uinteressant. Og ikke minst er det frustrerende å lese den samme nyheten gang på gang på gang. Denne redundansen av informasjon merket jeg meg raskt da jeg begynte å snuse på <a href="http://en.wikipedia.org/wiki/RSS">RSS</a>-teknologien. Jeg hadde abonnert på VG, Dagbladet og en rekke andre nasjonale nettaviser, i tillegg til noen få lokale. Nå skulle det ikke være noe problem å få full oversikt over nyhetsbildet i Norge tenkte jeg. Resultatet var en flom av tekster som omhandlet de samme nyhetene gang på gang, og i en slik mengde at jeg til slutt slettet alle nye meldingene jeg hadde fått fra avisene. De rett og slett overveldet min evne og vilje til å holde tritt med nyhetsbildet.</p>
<p>Utvelgelse var på sin plass (natural selection anyone?). Men hvilken skulle jeg velge? Følelsen var at jeg gjennom å velge bort en avis kunne miste evt. fremtidige, gode tekster. Min løsning fant jeg i <a href="http://news.google.no/">Google News Norge</a>. Slik jeg forsto løsningen prosesserte Google nyheter fra mange aviser og valgte ut de som var interessante for meg, evt. ga meg muligheten til å dykke enda dypere i nyheten gjennom en enkel oversikt over speil-tekstene. Kvalitet samtidig som man fikk kvantiteten! Så utrolig bra! Dette var iallefall tilfellet i min drømmeverden.</p>
<p><strong>En drømmeverden</strong></p>
<p>Google News Norge er nå den eneste nyhets<abbr title="mitt ord for feed for tiden=)">kanal</abbr>en jeg har. Med nyheter mener jeg her ordet i sin klassiske forstand, altså oppdateringer på innenriks, utenriks, sport, etc i sin generelle forstand. Det finnes mange andre kanaler der ute jeg kunne ha lagt til, men som jeg bevisst har latt være. Grunnen er enkel: Jeg har ikke interesse å bli mer hyppig oppdatert, ikke i bredere forstand.</p>
<p>Etter langt om lenge skal jeg nå begynne å nærme meg poenget mitt med denne teksten. Mengden informasjon der ute er enorm. Det er i vår natur å skjerme deler av den ute, vi klarer rett og slett ikke ta alt innover oss. Dette kan brukes som en metafor for samfunnet, som gjennom tidene har utviklet massemedia. Det moderne massemedia er utrolig komplisert av varianter og har et informasjonsinnhold jeg ikke tror kan sammenlignes med noen tidligere tider. Dette har blitt mulig gjennom internett og den revolusjonen/renessancen som har blitt gjennomført i weblogg-miljøet har multiplisert denne informasjonsmengden betraktelig.</p>
<p>Jeg føler at denne økte informasjonsmengden har ført til et skifte, et skifte som krever nye former for informasjonsbehandling. Med denne følelsen kommer en fornemmelse av hva som er riktig vei å gå, men denne fornemmelsen er splittet i to grunnleggende motstridende syn. I det ene ser jeg for meg at redaktør-rollen blir ivaretatt mye i samme grad som den finnes i dag, men at den får en oppgradering i form av at den klarer å takle den mengden med informasjon som kommer i dag. Effektivitet på en slik måte at redaktørene fungerer som et filter for leserskaren. I det andre ser jeg mulighetene som mekanikken i Google News Norge legger til grunn. Roboter søker gjennom informasjonen for oss og finner informasjonen vi ønsker oss. Dette er den teknisk letteste løsningen jeg kan se, da man etter å ha funnet “løsningen” ikke lenger trenger mennesker i mattestykket. Alt er automatisert.</p>
<p>I løsning nr 2 ser jeg også fallet. Da jeg leste <a href="http://depesjer.no/nyheter/meninger/kultur/naar_tiden_blir_knapp">Når tiden blir knapp</a> av Charlotte Sissener kom dette ytterligere klarere frem. Gjennom automatiseringen vil kreativiteten forsvinne. Om ikke forsvinne, bli langt sjeldnere. Og det er her jeg ser håpet i mennesket som redaktører igjen. Altså ikke redaktør som i at en liten gruppe sitter på et rom og bestemmer dagsorden for en hel nasjon, men redaktører som i hele folket vurderer informasjonen som kommer strømmende inn fra alle kanter. Dette er det jeg fornemmer i sosiale nettsider som <a href="http://www.stumbleupon.com/">StumbleUpon</a> og <a href="http://del.icio.us/">del.icio.us</a>. Jeg begynner med sistnevnte, som enklest kan beskrives som en sosial bokmerkingsside. Og når flere syns en side er bra (legger den til som bokmerke) så blir den lagt til del.icio.us’ hotlist, som oppdateres jevnlig. På den måten popper det inn nye sider som kan være av interesse. Skal jeg nevne en svakhet med dette systemet raskt er at <a href="http://digg.com/">digg</a>-effekten er å føle her og. Det vil si den effekten en side har av å komme på førstesiden til digg.com, enda en sosial side hvor man promoterer websider, men med en enda hissigere brukergruppe.</p>
<p>StumbleUpon derimot har jeg mere sansen for. Utformingen av dette sosiale konseptet har gjort til at man nærmest surfer gjennom nye sider som man surfer gjennom tv-kanaler i håp om å finne gode tv-programmer. Man trykker på en knapp oppe i venstre hjørne, og vips så er man inne på en ny side. Denne siden finner StumbleUpon gjennom preferanser du har ført opp tidligere og gjennom dine vurderinger (du kan si om du liker siden eller ikke underveis). Enkelt og greit genialt!</p>
<p>Løsningen til StumbleUpon er den løsningen jeg per dags dato er mest fornøyd med. Dette er kanskje litt ironisk, siden dette er løsningen som faktisk ikke viser meg hvor mange nye evt. kule sider det finnes der ute som jeg kan “oppdage”. Om noe kan sies ut fra det jeg har sagt til nå, så er jo noe av savnet mitt at jeg ikke kan få den totale oversikten over hvilke nettsider som ligger der ute som hadde appelert til meg.</p>
<p>Når alt kommer til alt, urealistiske ønsker til side, så er kanskje kompromisser det beste vi kan håpe på. Ikke full oversikt altså, men oppdager-gleden og -iveren inntakt.</p>
<p>Til slutt vil jeg lire av meg referansen <a href="http://www.aftenposten.no/meninger/kommentarer/article1678269.ece">Ja til bloggerne</a> av Hans Erik Matre, som er en velskrevet artikkel om bloggere, kvalitet, kvantitet og med noen gode kritikker.</p>

        </BlogPost>
    )
}